SPWSAppDeploymentAPINETFX/Controllers/ADController.cs
using Microsoft.AspNet.SignalR;
using SPWSAppDeploymentAPINETFX.Hubs;
using SPWSAppDeploymentAPINETFX.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace SPWSAppDeploymentAPINETFX.Controllers
{
    public class ADController : ApiController
    {
        //[Route("AD/GetServers")]
        //[HttpGet]
        //public string GetServers()
        //{
        //    string result = "";
        //    try
        //    {
        //        var devserverContext = new ServerInstance("172.17.147.86", "sa", "devdbsvr");
        //        var acsserverContext = new ServerInstance("172.17.147.71", "sa", "spwsadmin");
        //        var Dapps = devserverContext.Database.SqlQuery<App>("Select * FROM dbo.Apps").ToList();
        //        var Aapps = acsserverContext.Database.SqlQuery<App>("Select * FROM dbo.Apps").ToList();
        //        List<App> applist = new List<App>();
        //        applist.AddRange(Dapps);
        //        applist.AddRange(Aapps);
        //        result += Newtonsoft.Json.JsonConvert.SerializeObject(applist);
        //    }
        //    catch (Exception ex)
        //    {
        //        result = ex.ToString();
        //    }
        //    return result;
        //}

        [Route("AD/GetClients")]
        [HttpGet]
        public AppJsonResponse GetClients()
        {
            AppJsonResponse result = new AppJsonResponse();
            try
            {
                result.Data = Newtonsoft.Json.JsonConvert.SerializeObject(ADHub.sClients);
                result.Status = true;
            }
            catch (Exception ex)
            {
                result.Exception = ex.ToString();
            }
            return result;
        }

        [Route("AD/GetClientTask/{HostName}")]
        [HttpGet]
        public string GetClientTask(string HostName)
        {
            string result = "";

            try
            {
                var instance = GlobalHost.ConnectionManager.GetHubContext<ADHub>();
                var client = ADHub.sClients.FirstOrDefault(sc => sc.HostName == HostName);
                if (client == null)
                {
                    result = "Client Not Found!";
                }
                else
                {
                    var newServerRequest = new ADHub.ServerRequest()
                    {
                        RequestId = ADHub.sRequest.Count() + 1,
                        DateTime = DateTime.Now,
                        Task = "GetTask",
                        Status = ADHub.ServerRequestStatus.Pending,
                    };
                    ADHub.sRequest.Add(newServerRequest);
                    instance.Clients.Client(client.ConnectionId).getTask(newServerRequest.RequestId);
                    do
                    {
                        newServerRequest = ADHub.sRequest.ToList().FirstOrDefault(sr => sr.RequestId == newServerRequest.RequestId);
                        var interval = DateTime.Now.Subtract(newServerRequest.DateTime).TotalSeconds;
                        if (interval > 60)
                        {
                            break;
                        }
                    } while (newServerRequest.Status != ADHub.ServerRequestStatus.Success);
                    if (newServerRequest.Status == ADHub.ServerRequestStatus.Success)
                    {
                        result = ADHub.sRequest.FirstOrDefault(sr => sr.RequestId == newServerRequest.RequestId).Data;
                    }
                    else
                    {
                        result = "Request Timed Out!";
                    }
                }
            }
            catch (Exception ex)
            {
                result = ex.ToString();
            }
            return result;
        }


        [Route("AD/KillTask/{HostName}/{PID}")]
        [HttpGet]
        public string KillTask(string HostName,int PID)
        {
            string result = "";
            try
            {
                var instance = GlobalHost.ConnectionManager.GetHubContext<ADHub>();
                var client = ADHub.sClients.FirstOrDefault(sc => sc.HostName == HostName);
                if (client == null)
                {
                    result = "Client Not Found!";
                }
                else
                {
                    var newServerRequest = new ADHub.ServerRequest()
                    {
                        RequestId = ADHub.sRequest.Count() + 1,
                        DateTime = DateTime.Now,
                        Task = "KillTask",
                        Status = ADHub.ServerRequestStatus.Pending,

                    };
                    ADHub.sRequest.Add(newServerRequest);
                    instance.Clients.Client(client.ConnectionId).killTask(newServerRequest.RequestId,PID);
                    do
                    {
                        newServerRequest = ADHub.sRequest.ToList().FirstOrDefault(sr => sr.RequestId == newServerRequest.RequestId);
                        var interval = DateTime.Now.Subtract(newServerRequest.DateTime).TotalSeconds;
                        if (interval > 60)
                        {
                            break;
                        }
                    } while (newServerRequest.Status != ADHub.ServerRequestStatus.Success);
                    if (newServerRequest.Status == ADHub.ServerRequestStatus.Success)
                    {
                        result = ADHub.sRequest.FirstOrDefault(sr => sr.RequestId == newServerRequest.RequestId).Data;
                    }
                    else
                    {
                        result = "Request Timed Out!";
                    }
                }
            }
            catch (Exception ex)
            {
                result = ex.ToString();
                //throw;
            }
            return result;
        }

        [Route("AD/CustomTask/{HostName}/{TaskPath}/{Arguments}")]
        [HttpGet]
        public string CustomTask(string HostName,string TaskPath,string Arguments)
        {
            string result = "";
            string a = "";
            switch (a)
            {
                case "a":
                    {

                    }
                    break;
                default:
                    break;
            }
            return result;
        }
    }
}

SPWSAppDeploymentAPINETFX/Controllers/AppsController.cs
using SPWSAppDeploymentAPINETFX.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Http;

namespace SPWSAppDeploymentAPINETFX.Controllers
{
    public class AppsController : ApiController
    {
        [Route("Apps/GetServers")]
        [HttpGet]
        public AppJsonResponse GetServers()
        {
            AppJsonResponse result = new AppJsonResponse();
            try
            {
                List<ServerInstanceResponse> sir = new List<ServerInstanceResponse>();
                foreach (var item in ServerProfile.local.ToList())
                {
                    sir.Add(new ServerInstanceResponse()
                    {
                        IPAddress = item.IPAddress,
                        ServerName = item.ServerName
                    });
                }
                result.Data = Newtonsoft.Json.JsonConvert.SerializeObject(sir);
                result.Status = true; 
            }
            catch (Exception ex)
            {
                result.Exception = ex.ToString();
            }

            return result;
        }

        [Route("Apps/GetApps/{ServerName}")]
        [HttpGet]
        public AppJsonResponse GetApps(string ServerName)
        {
            AppJsonResponse result = new AppJsonResponse();
            try
            {
                ServerProfile sp = ServerProfile.local.FirstOrDefault(x => x.ServerName.Equals(ServerName));
                if (sp != null)
                {
                    ServerInstance si = ServerInstance.serverInstances.FirstOrDefault(s => s.IPAddress == sp.IPAddress);
                    result.Data = Newtonsoft.Json.JsonConvert.SerializeObject(si.lApps.OrderBy(x => x.AppId).ToList());
                    result.Status = true;
                }
                else
                {
                    result.Exception = $"Server not found: {ServerName}";
                }
            }
            catch (Exception ex)
            {
                result.Exception = ex.ToString();
            }
            return result;
        }

        [Route("Apps/GetVersions/{ServerName}/{AppId}")]
        [HttpGet]
        public AppJsonResponse GetVersions(string ServerName, int AppId)
        {
            AppJsonResponse result = new AppJsonResponse();
            try
            {
                ServerProfile sp = ServerProfile.local.FirstOrDefault(x => x.ServerName.Equals(ServerName));
                if (sp != null)
                {
                    var si = ServerInstance.serverInstances.FirstOrDefault(s => s.IPAddress == sp.IPAddress);
                    result.Data = Newtonsoft.Json.JsonConvert.SerializeObject(si.lAppVersion.Where(lAV => lAV.AppId == AppId).ToList());
                    result.Status = true;
                }
                else
                {
                    result.Exception = $"Server not found: {ServerName}";
                }
            }
            catch (Exception ex)
            {
                result.Exception = ex.ToString();
            }
            return result;
        }
        [Route("Apps/GetFiles/{ServerName}/{AppVersionId}")]
        public AppJsonResponse GetFiles(string ServerName, int AppVersionId)
        {
            AppJsonResponse result = new AppJsonResponse();
            try
            {
                ServerProfile sp = ServerProfile.local.FirstOrDefault(x => x.ServerName.Equals(ServerName));
                if (sp != null)
                {
                    ServerInstance si = ServerInstance.serverInstances.FirstOrDefault(s => s.IPAddress == sp.IPAddress);
                    result.Data = Newtonsoft.Json.JsonConvert.SerializeObject(si.lAppFiles.Where(lAF => lAF.AppVersionId == AppVersionId).ToList());
                    result.Status = true;
                }
                else
                {
                    result.Exception = $"Server not found: {ServerName}";
                }
            }
            catch (Exception ex)
            {
                result.Exception = ex.ToString();
            }
            return result;
        }

        [Route("Apps/GetFile/{ServerName}/{AppFileId}")]
        [HttpGet]
        public AppJsonResponse GetFile(string ServerName, int AppFileId)
        {
            AppJsonResponse result = new AppJsonResponse();
            try
            {
                ServerProfile sp = ServerProfile.local.FirstOrDefault(x => x.ServerName.Equals(ServerName));
                if (sp != null)
                {
                    ServerInstance si = ServerInstance.serverInstances.FirstOrDefault(s => s.IPAddress == sp.IPAddress);
                    AppFileBlob data = si.Database.SqlQuery<AppFileBlob>($"Select * From dbo.AppFileBlobs where AppFileId = {AppFileId}").First();
                    result.Data = Newtonsoft.Json.JsonConvert.SerializeObject(data);
                    result.Status = true;;
                }
                else
                {
                    result.Exception = $"Server not found: {ServerName}";
                }
            }
            catch (Exception ex)
            {
                result.Exception = ex.ToString();
            }
            return result;
        }

        [Route("Apps/CreateApp/{ServerName}/{AppName}")]
        [HttpGet]
        public AppJsonResponse CreateApp(string ServerName, string AppName)
        {
            AppJsonResponse result = new AppJsonResponse();
            try
            {
                ServerProfile sp = ServerProfile.local.FirstOrDefault(x => x.ServerName.Equals(ServerName));
                if (sp != null)
                {
                    var si = ServerInstance.serverInstances.FirstOrDefault(s => s.IPAddress == sp.IPAddress);
                    si.Apps.Add(new App()
                    {
                        AppName = AppName
                    });
                    si.SaveChanges();
                    si.lApps = si.Database.SqlQuery<App>("SELECT * FROM dbo.Apps").ToList();
                    result.Status = true;
                }
                else
                {
                    result.Exception = $"Server not found: {ServerName}";
                }
            }
            catch (Exception ex)
            {
                result.Exception = ex.ToString();
            }
            return result;
        }

        [Route("Apps/DeleteApp/{ServerName}/{AppName}")]
        [HttpGet]
        public AppJsonResponse DeleteApp(string ServerName, string AppName)
        {
            AppJsonResponse result = new AppJsonResponse();
            try
            {
                ServerProfile sp = ServerProfile.local.FirstOrDefault(x => x.ServerName.Equals(ServerName));
                if (sp != null)
                {
                    var si = ServerInstance.serverInstances.FirstOrDefault(s => s.IPAddress == sp.IPAddress);
                    var app = si.lApps.FirstOrDefault(a => a.AppName == AppName);
                    var appVersions = si.lAppVersion.Where(av => av.AppId == app.AppId).ToList();
                    foreach (var appVersion in appVersions)
                    {
                        var appFileIds = si.lAppFiles.Where(af => af.AppVersionId == appVersion.AppVersionId).Select(af => af.AppFileId).ToArray();
                        si.AppFileBlobs.RemoveRange(si.AppFileBlobs.Where(afb => appFileIds.Contains(afb.AppFileId)));
                        si.AppFiles.RemoveRange(si.AppFiles.Where(afb => appFileIds.Contains(afb.AppFileId)));

                    }
                    si.AppVersions.RemoveRange(si.AppVersions.Where(av => av.AppId == app.AppId));
                    si.Apps.Remove(si.Apps.FirstOrDefault(a => a.AppId == app.AppId));
                    si.SaveChanges();
                    si.lApps = si.Database.SqlQuery<App>("SELECT * FROM dbo.Apps").ToList();
                    si.lAppVersion = si.Database.SqlQuery<AppVersion>("SELECT * FROM dbo.AppVersions").ToList();
                    si.lAppFiles = si.Database.SqlQuery<AppFile>("SELECT * FROM dbo.AppFiles").ToList();
                    result.Status = true;
                }
                else
                {
                    result.Exception = $"Server not found: {ServerName}";
                }
            }
            catch (Exception ex)
            {
                result.Exception = ex.ToString();
            }
            return result;
        }

        [Route("Apps/AddVersion/{ServerName}/{AppName}/{AppVersionName}/{isMajorRevision}")]
        [HttpGet]
        public AppJsonResponse AddVersion(string ServerName,string AppName,string AppVersionName,bool isMajorRevision)
        {
            AppJsonResponse result = new AppJsonResponse();
            try
            {
                ServerProfile sp = ServerProfile.local.FirstOrDefault(x => x.ServerName.Equals(ServerName));
                if (sp != null)
                {
                    ServerInstance si = ServerInstance.serverInstances.FirstOrDefault(s => s.IPAddress == sp.IPAddress);
                    App app = si.lApps.FirstOrDefault(a => a.AppName == AppName);
                    si.AppVersions.Add(new AppVersion()
                    {
                        AppId = app.AppId,
                        AppVersionName = AppVersionName,
                        Date = DateTime.Now,
                        isMajorRevision = isMajorRevision
                    }) ;
                    si.SaveChanges();
                    si.lAppVersion = si.Database.SqlQuery<AppVersion>("SELECT * FROM dbo.AppVersions").ToList();
                    result.Status = true;
                }
                else
                {
                    result.Exception = $"Server not found: {ServerName}";
                }

            }
            catch (Exception ex)
            {
                result.Exception = ex.ToString();
            }

SPWSAppDeploymentAPINETFX/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <style>
        body {
            user-select: none;
        }
    </style>
    @Styles.Render("~/Content/css")
    <link rel="stylesheet" href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href='@Url.Content("~/Content/fontawesome/css/all.min.css")' />
    <link rel="stylesheet" href="@Url.Content("~/Content/alertify/css/alertify.min.css")" />
    @Scripts.Render("~/bundles/modernizr")

    <script>
        var getClientsUrl = '@Url.Action("GetClients","AD")';
        var getClientTaskUrl = '@Url.Action("GetClientTask","AD")';
        var killClientTaskUrl = '@Url.Action("KillTask","AD")';
        var getAppFilesUrl = '@Url.Action("GetFiles","Apps")';
        var getAppVersionUrl = '@Url.Action("GetVersions","Apps")';
        var getAppServersUrl = '@Url.Action("GetServers","Apps")';
        var getAppsUrl = '@Url.Action("GetApps","Apps")';
        var createAppsUrl = '@Url.Action("CreateApp", "Apps")';
        var deleteAppsUrl = '@Url.Action("DeleteApp","Apps")';
        var createAppVersionUrl = '@Url.Action("AddVersion","Apps")';
        var deleteAppVersionUrl = '@Url.Action("DeleteVersion","Apps")';
        var createDirectoryUrl = '@Url.Action("CreateDirectory","Apps")';
        var uploadFileUrl = '@Url.Action("UploadFiles","Apps")';
        var deleteMultiSelectUrl = '@Url.Action("DeleteMultiSelect","Apps")';
        var addGroupUrl = '@Url.Action("AddGroup","ClientProfile")';
        var deleteGroupUrl = '@Url.Action("DeleteGroup","ClientProfile")';
        var addGroupMembers = '@Url.Action("AddGroupMembers","ClientProfile")';
        var deleteGroupMembers = '@Url.Action("DeleteGroupMembers","ClientProfile")';
        var getGroups = '@Url.Action("GetGroups","ClientProfile")';
        var getGroupMembers = '@Url.Action("GetMembers","ClientProfile")';
        var getMemberDetails = '@Url.Action("GetMemberDetails","ClientProfile")';
        var getAppDetails = '@Url.Action("GetAppDetails","ClientProfile")';
        var restartClientConn = '@Url.Action("RestartHubCon","ClientProfile")'
    </script>
    <script>

    </script>
    @RenderSection("headerScripts", required: false)




</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("SPWS App Deployment", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Monitoring", "Monitoring", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Applications", "Applications", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Settings", "Settings", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container-fluid body-content">
        @RenderBody()
        <footer>
            <hr />
            <p>&copy; @DateTime.Now.Year - Sumi Philippines Wiring Systems Corp. | Information Technology</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script type="text/javascript" src='@Url.Content("~/Content/alertify/alertify.min.js")'></script>
    <script type="text/javascript" src='@Url.Content("~/Scripts/knockout-3.5.1.js")'></script>
    @*<script type="text/javascript" src="@Url.Content("~/Content/fontawesome/js/all.min.js")"></script>*@
    <script type="text/javascript" src='@Url.Content("~/Scripts/jquery.signalR-2.4.1.min.js")'></script>
    <script type="text/javascript" src='@Url.Content("~/adhub/signalr/hubs")'></script>
    @RenderSection("scripts", required: false)

  
</body>
</html>